This is your assignment on conditional statement and looping

**Problem-1**<br>
Write a small program to check a number is divisible by 7 or not

In [3]:
num=int(input('Enter any number:'))
if num%7==0:
  print('The number is divisible by 7.')
else:
  print('The number is not divisible by 7')

Enter any number:8
The number is not divisible by 7

**Problem-2**<br>
If a number is divisible by either 5 or 7, then we will call it a 'five-or-seven' number.<br> 
Write down a program to check if a number is 'five-or-seven' number or not.

In [ ]:
num=int(input('Enter any number:'))
if num%7==0 or num%5==0:
  print('The Number is a five-or-seven number.')
else:
  print('The Number is Not a five-or-seven number.')

**Problem-3**<br>
Write a program to calculate the electricity bill (accept number of unit from user) according to the following criteria:<br>  
Upto first 100 units Rs. 3 per unit.<br>
Next 100 units Rs. 5 per unit.<br>
Next 300 units Rs. 7 per unit.<br>
Above that, for each unit exceeding 500, Rs. 10 per unit flat.<br>

In [ ]:
nounits=int(input('Enter units consumed:'))
if nounits<=100:
  cost=3*nounits
elif 100<nounits>=200:
  cost=300+(nounits-100)*5
elif 200<nounits>=500:
  cost=800+(nounits-200)*7
else:
  cost=2900+(nounits-500)*10

print('Total Cost:',cost)

**Problem-4**<br>
Find out sum of square of all the numbers upto 10, starting from 1

In [ ]:
sum=0
for i in range(1,11):
  sum= sum+(i*i)
print('',sum)

**Problem-5**<br>
Find out sum of square of all the even numbers upto 10, starting from 1

In [ ]:
sum=0
for i in range(1,11):
  if i%2==0:
    sum=sum+(i*i)
  else:
    continue 
print('',sum)

**Problem-6**<br>
Check a number is prime or not

In [8]:
num=int(input('Enter a Number:'))
if num>1:
  for i in range(2,num):
    if num%i==0:
      print(num, 'is Not a Prime Number.')
      break
    else:
      print(num, 'is a Prime Number.')
      break
else:
    print(num,'is not a Prime Number.')

Enter a Number:83
83 is a Prime Number.

**Problem-7**<br>
Print multiplication table upto 10 starting from 1

In [9]:
for i in range (1,11):
  for j in range(1,11):
    product = j*i
    print(i,'*',j,'=',product)
    print('\t')
print('\n')

**Problem-8**<br>
Print the series of first n fibonacci numbers

In [11]:
n=int(input('Enter number of elements\n'))
a = 0
b = 1
if n==1:
  print(a)
else:
  print(a)
  print(b)
  for i in range(2,n):
    c=a+b
    a=b
    b=c
    print(c)

Enter number of elements
7
0
1
1
2
3
5
8